version: '2'
services:
    pdns-mailcow:
      image: andryyy/mailcow-dockerized:pdns
      volumes:
        - ./data/conf/pdns/:/etc/powerdns/
      restart: always
      networks:
        mailcow-network:
          ipv4_address: 172.22.1.254
          aliases:
            - pdns

    mysql-mailcow:
      image: mariadb:10.1
      depends_on:
        - pdns-mailcow
      command: mysqld
      volumes:
        - mysql-vol-1:/var/lib/mysql/
        - ./data/conf/mysql/:/etc/mysql/conf.d/:ro
      dns:
        - 172.22.1.254
      dns_search: mailcow-network
      environment:
        - MYSQL_ROOT_PASSWORD=${DBROOT}
        - MYSQL_DATABASE=${DBNAME}
        - MYSQL_USER=${DBUSER}
        - MYSQL_PASSWORD=${DBPASS}
      restart: always
      networks:
        mailcow-network:
          aliases:
            - mysql

    redis-mailcow:
      image: redis
      depends_on:
        - pdns-mailcow
      volumes:
        - redis-vol-1:/data/
      restart: always
      dns:
        - 172.22.1.254
      dns_search: mailcow-network
      networks:
        mailcow-network:
          aliases:
            - redis

    rspamd-mailcow:
      image: andryyy/mailcow-dockerized:rspamd
      depends_on:
        - pdns-mailcow
      volumes:
        - ./data/conf/rspamd/override.d/:/etc/rspamd/override.d:ro
        - ./data/conf/rspamd/local.d/:/etc/rspamd/local.d:ro
        - ./data/conf/rspamd/lua/:/etc/rspamd/lua/:ro
        - dkim-vol-1:/data/dkim
      restart: always
      dns: 
        - 172.22.1.254
      dns_search: mailcow-network
      networks:
        mailcow-network:
          aliases:
            - rspamd

    php-fpm-mailcow:
      image: andryyy/mailcow-dockerized:phpfpm
      depends_on:
        - pdns-mailcow
      volumes:
        - ./data/web:/web:ro
        - ./data/conf/rspamd/dynmaps:/dynmaps:ro
        - dkim-vol-1:/data/dkim
      dns:
        - 172.22.1.254
      dns_search: mailcow-network
      environment:
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
        - TZ=${TZ}
      restart: always
      networks:
        mailcow-network:
          aliases:
            - phpfpm

    sogo-mailcow:
      image: andryyy/mailcow-dockerized:sogo
      depends_on:
        - pdns-mailcow
        - mysql-mailcow
      environment:
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
        - TZ=${TZ}
      dns:
        - 172.22.1.254
      dns_search: mailcow-network
      volumes:
        - ./data/conf/sogo/:/etc/sogo/
        - /usr/lib/GNUstep/SOGo/WebServerResources/
      restart: always
      networks:
        mailcow-network:
          aliases:
            - sogo

    rmilter-mailcow:
      image: andryyy/mailcow-dockerized:rmilter
      depends_on:
        - pdns-mailcow
      volumes:
        - ./data/conf/rmilter/:/etc/rmilter.conf.d/:ro
      restart: always
      dns:
        - 172.22.1.254
      dns_search: mailcow-network
      networks:
        mailcow-network:
          aliases:
            - rmilter

    dovecot-mailcow:
      image: andryyy/mailcow-dockerized:dovecot
      depends_on:
        - pdns-mailcow
      volumes:
        - ./data/conf/dovecot:/etc/dovecot
        - ./data/assets/ssl:/etc/ssl/mail/:ro
        - vmail-vol-1:/var/vmail
      volumes_from:
        - sogo-mailcow
      environment:
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
      ports:
        - "${IMAP_PORT}:143"
        - "${IMAPS_PORT}:993"
        - "${POP_PORT}:110"
        - "${POPS_PORT}:995"
        - "${SIEVE_PORT}:4190"
      dns:
        - 172.22.1.254
      dns_search: mailcow-network
      restart: always
      hostname: ${MAILCOW_HOSTNAME}
      networks:
        mailcow-network:
          aliases:
            - dovecot

    postfix-mailcow:
      image: andryyy/mailcow-dockerized:postfix
      depends_on:
        - pdns-mailcow
      volumes:
        - ./data/conf/postfix:/opt/postfix/conf
        - ./data/assets/ssl:/etc/ssl/mail/:ro
      environment:
        - DBNAME=${DBNAME}
        - DBUSER=${DBUSER}
        - DBPASS=${DBPASS}
      ports:
        - "${SMTP_PORT}:25"
        - "${SMTPS_PORT}:465"
        - "${SUBMISSION_PORT}:587"
      restart: always
      hostname: ${MAILCOW_HOSTNAME}
      dns: 
        - 172.22.1.254
      dns_search: mailcow-network
      networks:
        mailcow-network:
          aliases:
            - postfix

    memcached-mailcow:
      image: memcached
      depends_on:
        - pdns-mailcow
      restart: always
      dns:
        - 172.22.1.254
      dns_search: mailcow-network
      networks:
        mailcow-network:
          aliases:
            - memcached

    nginx-mailcow:
      depends_on:
        - mysql-mailcow
        - sogo-mailcow
        - php-fpm-mailcow
        - rspamd-mailcow
      image: nginx:mainline
      volumes_from:
        - sogo-mailcow
      volumes:
        - ./data/web:/web:ro
        - ./data/conf/rspamd/dynmaps:/dynmaps:ro
        - ./data/assets/ssl/:/etc/ssl/mail/:ro
        - ./data/conf/nginx/:/etc/nginx/conf.d/:ro
      dns:
        - 172.22.1.254
      dns_search: mailcow-network
      ports:
        - "443:443"
        - "80:80"
      restart: always
      networks:
        mailcow-network:
          aliases:
            - nginx

networks:
  mailcow-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.1.0/24
          gateway: 172.22.1.1

volumes:
  vmail-vol-1:
  mysql-vol-1:
  dkim-vol-1:
  redis-vol-1:
